/* eslint-disable react/no-unescaped-entities */
import { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { Box, Button, Flex, Text } from "@chakra-ui/react";
import { ContainerPage } from "../styles/ContainerPage";
import { Link } from "react-scroll";
import { DownloadIcon } from "@chakra-ui/icons";
import Image from "next/image";
import { Amar } from "../assets";
import { motion } from "framer-motion";

const MotionBox = motion(Box);

const About: NextPage = () => {
  return (
    <ContainerPage id="about" minHeight="100vh" pt="70px">
      <Head>
        <title>Amar's Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction="column" gap="10px">
        <Text textAlign="center" fontSize="3xl">
          About
        </Text>
        <Text textAlign="center" as="i" fontSize={14}>
          I'm Here To Help Your Next Project
        </Text>
        <Flex gap="24px" flexWrap="wrap" alignItems="start">
          <Box minWidth="350px" flex={1}>
            <Text alignSelf="center" textAlign="justify">
              I'm Amar Smajlović. From my earliest days at the age of 5, I've
              been captivated by technology, starting with the enchanting world
              of video games. I value honesty and transparency, and I've carried
              that ethos into my journey in the world of technology and
              computers. Although I've cherished technology throughout my life,
              my earliest passion was football. Unfortunately, in 2020, an
              injury changed the course of my life, leading me to the realm of
              programming. This shift marked the beginning of a new chapter,
              where programming swiftly became my foremost focus.
              <br />
              <br />I took my first steps into programming through a coding
              academy, where I penned my inaugural lines of code. This ignited a
              fire within me, propelling me to become a self-taught developer.
              My unyielding determination drove me to navigate the intricate
              coding landscape independently, always pushing my boundaries.
              <br />
              <br />
              While I deeply value self-guided learning, I also appreciate the
              power of collaboration. While I'm capable of taking on challenges
              solo, I recognize the strength in seeking diverse perspectives.
              This fusion of independent expertise and collaborative insight
              forms the foundation of my approach.
              <br />
              <br />I don't just write code; I craft digital experiences. My
              commitment to rapid learning and adaptability sets me apart. With
              every project, I delve in with unwavering curiosity, staying at
              the forefront of the latest tools and techniques. I'm not just a
              developer; I'm an evolving force, breathing life into innovation.
              <br />
              <br />
              Let's join forces and bring your vision to life. If you're looking
              to collaborate, don't hesitate to reach out to me. Feel free to
              <Link
                style={{
                  marginLeft: "5px",
                  fontWeight: 600,
                  cursor: "pointer",
                  color: "red",
                }}
                to="contact"
              >
                contact me
              </Link>
              .
            </Text>
          </Box>
          <Box height="full" flex={1}>
            <Box
              borderWidth="2px"
              borderRadius="50%"
              height="250px"
              width="250px"
              margin="auto"
              overflow="hidden"
            >
              <MotionBox
                height="100%"
                width="100%"
                position="relative"
                whileHover={{ scale: 1.3 }}
                transition={{ duration: 0.5 }}
              >
                <Image layout="fill" objectFit="cover" src={Amar} alt="amar" />
              </MotionBox>
            </Box>
            <Text mb="24px" fontSize="2xl" fontWeight={600}>
              Education
            </Text>
            <Flex direction="column" gap="12px">
              <Box padding="20px" borderWidth="1px" borderRadius="lg">
                <Text fontSize="small" color="gray" size="small">
                  September 1, 2015 - May 14 2018
                </Text>
                <Text>
                  High School of Traffic, Sarajevo - Department of Communication
                  Technologies
                </Text>
              </Box>
              <Box padding="20px" borderWidth="1px" borderRadius="lg">
                <Text fontSize="small" color="gray" size="small">
                  February 15, 2020 - Octomber 20 2020
                </Text>
                <Text>ITAcademy, Sarajevo - Frontend Developer</Text>
              </Box>
              <Button
                style={{ textDecoration: "none" }}
                as="a"
                href="AmarResume.pdf"
                download
                width="full"
                alignSelf="end"
              >
                <Text mr="4px">RESUME</Text>
                <DownloadIcon />
              </Button>
            </Flex>
          </Box>
        </Flex>
      </Flex>
    </ContainerPage>
  );
};

export default About;
