/* eslint-disable react/no-unescaped-entities */
import { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { Flex, Text } from "@chakra-ui/react";
import { ContainerPage } from "../styles/ContainerPage";

const About: NextPage = () => {
  return (
    <ContainerPage height="100vh" pt="70px">
      <Head>
        <title>Amar's Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction="column" gap="10px">
        <Text textAlign="center" fontSize="3xl">
          About
        </Text>
        <Text textAlign="justify">
          I am Software Developer specificied on frontend but also can do
          backend as well if Company requires. Passionate about creating
          interactive applications and experiences on the web. I'm open to Job
          opportunities where I can contribute, learn and grow. If you have a
          good opportunity that matches my skills and experience then don't
          hesitate to contact me.
        </Text>
      </Flex>
    </ContainerPage>
  );
};

export default About;
