/* eslint-disable react/no-unescaped-entities */
import { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { Flex, Text } from "@chakra-ui/react";
import { ContainerPage } from "../styles/ContainerPage";
import { ModalResume } from "../components";

const About: NextPage = () => {
  return (
    <ContainerPage id="about" height="100vh" pt="70px">
      <Head>
        <title>Amar's Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction="column" gap="10px">
        <Text textAlign="center" fontSize="3xl">
          About
        </Text>
        <Text textAlign="center" as="i" fontSize={14}>
          Hi, I'm Here To Help Your Next Project
        </Text>
        <Text textAlign="justify">
          I am a Software Developer who specializes in developing the front-end
          of websites and web applications that contribute to the overall
          success of the product. I can also do some back-end work if your
          project requires it. I am passionate about developing interactive web
          applications and experiences. I enjoy writing code from scratch and
          bringing ideas to life in the browser. I'm interested in jobs where I
          can contribute, learn, and grow. Please contact me if you have an
          excellent opportunity that matches my skills and experience.
        </Text>
        <ModalResume />
      </Flex>
    </ContainerPage>
  );
};

export default About;
