/* eslint-disable react/no-unescaped-entities */
import { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { Flex, Text } from "@chakra-ui/react";
import { ContainerPage } from "../styles/ContainerPage";
import { ExperienceCard } from "../components";
import { ExperienceCardType } from "../types";
import {
  CssIcon,
  FirebaseIcon,
  GotivaIcon,
  HtmlIcon,
  JavaScriptIcon,
  JestJSIcon,
  MopIcon,
  NextJSIcon,
  ReactIcon,
  TypescriptIcon,
} from "../assets";
import Image from "next/image";

const experiences: ExperienceCardType[] = [
  {
    companyLogo: <MopIcon center />,
    role: "Frontend Developer",
    workDate: "September 2022 - Present",
    techUsed: [
      { image: HtmlIcon, alt: "html-icon" },
      { image: CssIcon, alt: "css-icon" },
      { image: JavaScriptIcon, alt: "js-icon" },
      { image: ReactIcon, alt: "react-icon" },
      { image: TypescriptIcon, alt: "ts-icon" },
    ],
    description: [
      "Write code that is modern, performant, and maintainable for a wide range of client and internal projects.",
      "Work with a wide range of languages, platforms, frameworks, and content management systems, including JavaScript, TypeScript, and React.",
      "On a daily basis, communicate with multidisciplinary teams of engineers, designers, producers, and clients.",
    ],
  },
  {
    companyLogo: (
      <Image height="40px" width="170px" src={GotivaIcon} alt="gotiva-icon" />
    ),
    role: "Web Developer",
    workDate: "December 2021 - September 2022",
    techUsed: [
      { image: HtmlIcon, alt: "html-icon" },
      { image: CssIcon, alt: "css-icon" },
      { image: JavaScriptIcon, alt: "js-icon" },
      { image: ReactIcon, alt: "react-icon" },
      { image: TypescriptIcon, alt: "ts-icon" },
      { image: NextJSIcon, alt: "next-js-icon" },
      { image: FirebaseIcon, alt: "firebase-icon" },
      { image: JestJSIcon, alt: "jest-icon" },
    ],
    description: [
      "Developed and maintained code for in-house HTML, CSS, JavaScript, ReactJs, Typescript, NextJS, Firebase.",
      "Manually tested sites in various browsers and mobile devices to ensure cross-browser compatibility and responsiveness",
      "Figma design to React converting that is pixel-perfect.",
      "Creating reusable components, cloud functions in Firebase, and unit tests were also constructed using Jest.",
      "Informing clients and investors directly about the status of their applications.",
      "Learned about the new web development trends, technologies, and standards.",
    ],
  },
];

const Experience: NextPage = () => {
  return (
    <ContainerPage id="experience" height="100vh" pt="70px">
      <Head>
        <title>Amar's Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction="column" justifyContent="space-between" gap="10px">
        <Text textAlign="center" fontSize="3xl">
          Experience
        </Text>
        <Text as="i" textAlign="center" fontSize={14}>
          My Journey as Developer
        </Text>
        <Flex
          scrollSnapType="x mandatory"
          gap="10px"
          width="full"
          overflowX="scroll"
        >
          {experiences.map((experience, index) => (
            <ExperienceCard
              key={index}
              companyLogo={experience.companyLogo}
              role={experience.role}
              workDate={experience.workDate}
              techUsed={experience.techUsed}
              description={experience.description}
            />
          ))}
        </Flex>
      </Flex>
    </ContainerPage>
  );
};

export default Experience;
