/* eslint-disable react/jsx-no-undef */
/* eslint-disable react/no-unescaped-entities */
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { HeroImageAmar } from "../assets";
import { SocialIcons, TypeWriter } from "../components";
import { Flex, Text, Button, Box } from "@chakra-ui/react";
import { ContainerPage } from "../styles/ContainerPage";
import { motion } from "framer-motion";

const MotionBox = motion(Button);

const Hero: NextPage = () => {
  return (
    <ContainerPage id="home" height="100vh" pt="50px">
      <Head>
        <title>Amar's Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        height="100%"
        justifyContent="center"
        alignItems="center"
        gap="10px"
        direction="column"
      >
        <Box
          position="relative"
          width={{ base: 300, md: 350, lg: 400 }}
          height={{ base: 300, md: 350, lg: 400 }}
        >
          <Image
            layout="fill"
            priority
            quality={100}
            src={HeroImageAmar}
            alt="amar-hero-image"
          />
        </Box>
        <Text fontSize={14} textAlign="center" as="i">
          Software Developer
        </Text>
        <TypeWriter />
        <SocialIcons />
        <MotionBox
          borderRadius="9999px"
          variant="outline"
          size="md"
          colorScheme="white"
          initial={{ opacity: 0, x: -100 }}
          whileInView={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.2 }}
          whileHover={{ scale: 1.05 }}
        >
          GET IN TOUCH
        </MotionBox>
      </Flex>
    </ContainerPage>
  );
};

export default Hero;
