/* eslint-disable react/jsx-no-undef */
/* eslint-disable react/no-unescaped-entities */
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { HeroImageAmar } from "../assets";
import { SocialIcons, TypeWriter } from "../components";
import { Flex, Text, Button, Container } from "@chakra-ui/react";
import styled from "@emotion/styled";

const ContainerStyled = styled(Container)`
  scroll-snap-align: center;
`;

const Hero: NextPage = () => {
  return (
    <ContainerStyled height="100vh" pt="50px">
      <Head>
        <title>Amar's Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        height="100%"
        justifyContent="center"
        alignItems="center"
        gap="10px"
        direction="column"
      >
        <Image
          priority
          quality={100}
          src={HeroImageAmar}
          alt="amar-hero-image"
        />
        <Text textAlign="center" as="i">
          SOFTWARE DEVELOPER
        </Text>
        <TypeWriter />
        <SocialIcons />
        <Button variant="outline" size="lg" colorScheme="blue">
          GET IN TOUCH
        </Button>
      </Flex>
    </ContainerStyled>
  );
};

export default Hero;
