/* eslint-disable react/jsx-no-undef */
/* eslint-disable react/no-unescaped-entities */
import { Flex } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { JavaScriptIcon } from "../assets";
import { ITAcademyProject } from "../assets/ProjectsImage";
import { ProjectCard } from "../components";
import { ContainerPage } from "../styles/ContainerPage";

const projectsData = [
  {
    projectName: "E-Commerce Fullstack Web app",
    projectImage: ITAcademyProject,
    techUsed: [{ alt: "JavaScript", image: JavaScriptIcon }],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae mollitia assumenda minima obcaecati quae asperiores, laborum iste vitaererum. Officiis aspernatur minus ipsa deleniti dicta ab laudantium,consectetur non ut illo esse optio asperiores numquam blanditiis enimdoloremque nobis nihil.",
  },
  {
    projectName: "E-Commerce Fullstack Web app",
    projectImage: ITAcademyProject,
    techUsed: [{ alt: "JavaScript", image: JavaScriptIcon }],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae mollitia assumenda minima obcaecati quae asperiores, laborum iste vitaererum. Officiis aspernatur minus ipsa deleniti dicta ab laudantium,consectetur non ut illo esse optio asperiores numquam blanditiis enimdoloremque nobis nihil.",
  },
  {
    projectName: "E-Commerce Fullstack Web app",
    projectImage: ITAcademyProject,
    techUsed: [{ alt: "JavaScript", image: JavaScriptIcon }],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae mollitia assumenda minima obcaecati quae asperiores, laborum iste vitaererum. Officiis aspernatur minus ipsa deleniti dicta ab laudantium,consectetur non ut illo esse optio asperiores numquam blanditiis enimdoloremque nobis nihil.",
  },
];

const Projects: NextPage = () => {
  return (
    <ContainerPage id="projects" height="100vh" pt="50px">
      <Head>
        <title>Amar's Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        scrollSnapType="x mandatory"
        gap="5px"
        width="full"
        overflowX="scroll"
      >
        {projectsData.map((project) => (
          <ProjectCard
            projectImage={project.projectImage}
            projectName={project.projectName}
            techUsed={project.techUsed}
            description={project.description}
          />
        ))}
      </Flex>
    </ContainerPage>
  );
};

export default Projects;
