/* eslint-disable react/no-unescaped-entities */
import { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { Flex, Text, Grid } from "@chakra-ui/react";
import { ContainerPage } from "../styles/ContainerPage";
import { Skill } from "../components";
import { motion } from "framer-motion";
import {
  CssIcon,
  FirebaseIcon,
  HtmlIcon,
  JavaScriptIcon,
  JestJSIcon,
  MySQLIcon,
  NextJSIcon,
  NodeJSIcon,
  ReactIcon,
  TypescriptIcon,
  AngularIcon,
  ProblemSolvingIcon,
  CreativeIdeaIcon,
  HighQualityIcon,
} from "../assets";

const Skills: NextPage = () => {
  return (
    <ContainerPage id="skills" height="100vh" pt="70px">
      <Head>
        <title>Amar's Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1 }}
        transition={{ duration: 1.5 }}
      >
        <Flex direction="column" gap="10px">
          <Text textAlign="center" fontSize="3xl">
            Skills
          </Text>
          <Text textAlign="center" fontSize={14} as="i">
            Let's see my skills
          </Text>
          <Grid placeItems="center" templateColumns="repeat(3, 1fr)" gap="10px">
            <Skill src={HtmlIcon} />
            <Skill src={CssIcon} />
            <Skill src={JavaScriptIcon} />
            <Skill src={TypescriptIcon} />
            <Skill src={AngularIcon} />
            <Skill src={ReactIcon} />
            <Skill src={NextJSIcon} />
            <Skill src={NodeJSIcon} />
            <Skill src={MySQLIcon} />
            <Skill src={FirebaseIcon} />
            <Skill src={JestJSIcon} />
          </Grid>
          <Text textAlign="center" fontSize={14} as="i">
            Other Skills
          </Text>
          <Flex flexDirection="column">
            <Skill title="Problem Solving" image={<ProblemSolvingIcon />} />
            <Skill title="Creative Idea" image={<CreativeIdeaIcon />} />
            <Skill title="High Quality" image={<HighQualityIcon />} />
          </Flex>
        </Flex>
      </motion.div>
    </ContainerPage>
  );
};

export default Skills;
